core/PetStore/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.principal, name='principal'),
    path('mascotas', views.mascotas, name='mascotas'),
    path('perros', views.perros, name='perros'),
    path('gatos', views.gatos, name='gatos'),
    path('productos', views.productos, name='productos'),
    path('higiene', views.higiene, name='higiene'),
    path('accesorios', views.accesorios, name='accesorios'),
    path('alimentos', views.alimentos, name='alimentos'),
    path('registro', views.registro, name='registro'),
    path('login',views.conectar, name="login"),
    path('logout',views.desconectar, name='logout'),
    path('carrito', views.carrito, name='carrito'),
    ]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('PetStore.urls'))
]

core/PetStore/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class Region(models.Model):
    id_region = models.IntegerField(primary_key=True, db_column="idRegion")
    nombre = models.CharField(max_length=200, blank=False, null=False)
    
    def __str__(self):
        return str(self.nombre)
    
class Usuario(AbstractUser):
    direccion = models.CharField(max_length=255, db_column="direccion", blank=True, null=True)
    region = models.ForeignKey("Region", on_delete=models.CASCADE, db_column="idRegion", blank=True, null=True)
    cod_zip = models.CharField(max_length=20, db_column="codZip", blank=True, null=True)
    

    def __str__(self):
        return (
            str (self.email)
            +" "
            +str (self.username)
            +" "
            +str(self.last_name))
    
class TipoProducto(models.Model):
    id_tipo = models.IntegerField(primary_key=True, db_column="idTipo")
    tipo = models.CharField(max_length=200, blank=False, null=False)
    
class Productos(models.Model):
    id_prod = models.IntegerField(unique=True, primary_key=True, db_column="idProducto")
    nombre = models.CharField(max_length=100, db_column="Nombre")
    desc = models.CharField(max_length=5000, db_column="Descripcion")
    precio = models.IntegerField(db_column="Precio")
    tipo = models.ForeignKey("TipoProducto", on_delete=models.CASCADE, db_column="Tipo")


class TipoAnimal(models.Model):
    id_tipo = models.IntegerField(unique=True, primary_key=True,db_column="Tipo_Animal")
    tipo = models.CharField(max_length=200,blank=False, null=False )

class Animal(models.Model):
    id_animal = models.IntegerField(unique=True, primary_key=True, db_column="idAnimal")
    tipo = models.ForeignKey("TipoAnimal", on_delete=models.CASCADE, db_column="Tipo")
    nombre = models.CharField(max_length=20, db_column="Nombre" )
    desc = models.CharField(max_length=5000, db_column="Descripcion")
    raza = models.CharField(max_length=50, db_column="Raza")

core/PetStore/forms.py
from django import forms
from .models import Region, Usuario, TipoProducto, Productos, TipoAnimal, Animal
from django.contrib.auth.forms import AuthenticationForm
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class RegistroUser(UserCreationForm):
    class Meta:
        model = Usuario
        fields = ('username', 'email', 'password1', 'password2', 'last_name', 'direccion', 'region', 'cod_zip')
    
    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Las contraseñas no coinciden.")
        
        return password2

class LoginUser(AuthenticationForm):
    username = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'autofocus': True}))
    password = forms.CharField(label='Contraseña', strip=False, widget=forms.PasswordInput)

core/PetStore/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from .forms import RegistroUser, LoginUser
from .models import Usuario, Region
from django.contrib.auth.decorators import login_required
from django.utils import timezone

# Create your views here.
def principal(request):
    return render(request, 'pages/principal.html')

def mascotas(request):
    return render(request, 'pages/mascotas.html')

def perros(request):
    return render(request, 'pages/perros.html')

def gatos(request):
    return render(request, 'pages/gatos.html')

def productos(request):
    return render(request, 'pages/productos.html')

def higiene(request):
    return render(request, 'pages/higiene.html')

def alimentos(request):
    return render(request, 'pages/alimentos.html')

def accesorios(request):
    return render(request, 'pages/accesorios.html')

def carrito(request):
    return render(request, 'pages/carrito.html')

def registro(request):
    if request.method == 'POST':
        print("funciona 1")
        form = RegistroUser(request.POST)
        form.date_joined=timezone.now
        if form.is_valid():
            print("Funciona 2")
            user = form.save()
            login(request, user)
            return redirect('principal')
        else:
            print("no funciona")
            #print(request.POST)
            #print(form.errors)
            form = RegistroUser()
            context = {
                "mensaje":"No funciona",
                "form":form
            }
            return render(request,"registro.html",context)
    else:
        form = RegistroUser()
    return render(request, 'registro.html', {'form': form})

def conectar(request):
    if request.method == 'POST':
        form = LoginUser(request, data=request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=email, password=password)
            if user is not None:
                login(request, user)
                return redirect('principal')
            else:
                form.add_error(None, 'Email o contraseña incorrectos.')
    else:
        form = LoginUser()
    return render(request, 'login.html', {'form': form})

@login_required
def desconectar(request):
    logout(request)
    return redirect('principal')

core/PetStore/templates/base/footer.html
{%load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
<link rel="stylesheet" href="{% static 'css/style.css'%}">

<footer class="bg-dark text-white mt-5">
    <div class="container py-4">
        <div class="row">
            <h4>CONTACTO</h4>
            <hr>
            <div class="col-md-6">
                <p>Teléfono: <a href="tel:+56954181130" class="text-white">+569 541 1130</a></p>
                <p>WhatsApp: <a href="https://wa.me/56973947364" class="text-white" target="_blank">+569 739 47364</a></p>
                <p>Teléfono Fijo: <a href="tel:+56994781389" class="text-white">+569 947 81389</a></p>
            </div>
            <div class="col-md-6">
                <p>Email: <a href="mailto:fel.quezadar@duocuc.cl" class="text-white">fel.quezadar@duocuc.cl</a></p>
                <p>Email: <a href="mailto:cris.lara@duocuc.cl" class="text-white">cris.lara@duocuc.cl</a></p>
                <p>Email: <a href="mailto:be.pinones@duocuc.cl" class="text-white">be.pinones@duocuc.cl</a></p>
            </div>
        </div>
    </div>

    <script src="{% static 'js/funcion.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</footer>

core/PetStore/templates/base/header.html
<!-- TODO: Inicio NavBar -->
{%load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
<link rel="stylesheet" href="{% static 'css/style.css'%}">
<link rel="stylesheet" href="{% static 'css/s.carrito.css' %}">
<header class="content">
    <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
        <div class="container-fluid justify-content-center">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <a href="{% url "principal" %}"><img src="../static/img/Logo_pagina.png" alt="100" height="100"></a>
            <div class="collapse navbar-collapse justify-content-center" id="navbarNavDropdown">
                <ul class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url "principal" %}">Principal</a>
                </ul>
                <ul>
                    ||
                </ul>
                <ul class="nav-item">
                    <a class="nav-link active" href="{% url "mascotas" %}">Mascotas</a>
                </ul>
                <ul>
                    ||
                </ul>
                <ul class="nav-item">
                    <a class="nav-link active" href="{% url "productos" %}">Productos</a>
                </ul>
            </div>
            <div class="col-1">
                <a href="{% url "login" %}">
                    <img src="../static/img/login.png" alt="100" height="50">
                </a>
            </div>
            <div class="container-icon">
				<div class="container-cart-icon">
					<svg
						xmlns="http://www.w3.org/2000/svg"
						fill="none"
						viewBox="0 0 24 24"
						stroke-width="1.5"
						stroke="currentColor"
						class="icon-cart"
					>
						<path
							stroke-linecap="round"
							stroke-linejoin="round"
							d="M15.75 10.5V6a3.75 3.75 0 10-7.5 0v4.5m11.356-1.993l1.263 12c.07.665-.45 1.243-1.119
							1.243H4.25a1.125 1.125 0 01-1.12-1.243l1.264-12A1.125 1.125 0 015.513 7.5h12.974c.576 0 1.059.435 1.119 1.007zM8.625 10.5a.375.375 0 11-.75 0
							.375.375 0 01.75 0zm7.5 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z"
						/>
					</svg>
					<div class="count-products">
						<span id="contador-productos">0</span>
					</div>
				</div>  
        </div>
    </nav>
</header>

{% comment %} TODO: modalLogin {% endcomment %}
<div class="modal fade" id="modalLogin" tabindex="-1" aria-labelledby="modalLogin" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Iniciar Sesión</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="{% url 'login'%}" method="POST">
            {% csrf_token %}
            <div class="modal-body">
                    <div class="mb-3">
                        <label for="email" class="form-label">Correo</label>
                        <input type="email" class="form-control" id="email" name="email">
                    </div>
                    <div class="mb-3">
                        <label for="pass" class="form-label">Contraseña</label>
                        <input type="password" class="form-control" id="pass1" name="pass1">
                    </div>
            </div>
            <div class="modal-footer justify-content-start">
                <button type="submit" class="btn btn-dark">Iniciar Sesión</button>
                <a href="{% url "registro" %}"> 
                    <button type="btn" class="btn btn-outline-dark justify-content-start">Registrarse</button>
                </a>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
        
        
        </form>
    </div>
</div>

core/PetStore/templates/base/modalProductos.html
{%load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
<link rel="stylesheet" href="{% static 'css/style.css'%}">

<!-- Modal castilloGato -->
<div class="modal fade" id="modalCastilloGato" tabindex="-1" aria-labelledby="modalCastilloGato" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h1 class="modal-title fs-5" id="modalCastilloGato">Castillo de Gato</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <img src="../static/img/Productos/Accesorios/CastilloMascota.jpg" alt="100" height="300" width="300">
            <hr>
            El Castillo de Gato es el juguete perfecto para tu felino consentido, 
            ofreciendo diversión y confort en múltiples niveles. Construido con materiales duraderos y suaves,
            proporciona un refugio seguro para jugar, descansar y afilar las garras de tu gato.
            <p id="modalText">
                <br>

            </p>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Salir</button>
            <a href=""> <!-- *Link al perro -->
                <button type="button" class="btn btn-primary">Not Exit</button> 
            </a>
        </div>
        </div>
    </div>
</div>

{% comment %} modalAlfombra {% endcomment %}
<div class="modal fade" id="modalAlfombraGato" tabindex="-1" aria-labelledby="modalAlfombraoGato" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h1 class="modal-title fs-5" id="modalAlfombraoGato">Castillo de Gato</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <img src="../static/img/Productos/Higiene/AlfrombraGato.jpg" alt="100" height="300" width="300">
            <hr>
            Una solución práctica para mantener la limpieza alrededor del arenero de tu gato, 
            capturando eficazmente la arena y los residuos con su diseño texturizado y fácil de limpiar.
            <p id="modalText">
                <br>

            </p>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Salir</button>
            <a href=""> <!-- *Link al perro -->
                <button type="button" class="btn btn-primary">Not Exit</button> 
            </a>
        </div>
        </div>
    </div>
</div>

{% comment %} modalCollarCuero {% endcomment %}
<div class="modal fade" id="modalCollarCuero" tabindex="-1" aria-labelledby="modalCollarCuero" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h1 class="modal-title fs-5" id="modalCollarCuero">Castillo de Gato</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <img src="../static/img/Productos/Accesorios/CollarCuero.jpg" alt="100" height="300" width="300">
            <hr>
            Un elegante collar para mascotas fabricado con cuero sintético, ideal para perros y gatos. 
            Combina durabilidad con un estilo clásico, ofreciendo comodidad y resistencia al desgaste.
            <p id="modalText">
                <br>

            </p>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Salir</button>
            <a href=""> <!-- *Link al perro -->
                <button type="button" class="btn btn-primary">Not Exit</button> 
            </a>
        </div>
        </div>
    </div>
</div>

{% comment %} modalComidaMascota {% endcomment %}
<div class="modal fade" id="modalComidaMascota" tabindex="-1" aria-labelledby="modalComidaMascota" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h1 class="modal-title fs-5" id="modalComidaMascota">Castillo de Gato</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <img src="../static/img/Productos/Alimentacion/Comida de Mascota.jpg" alt="100" height="300" width="300">
            <hr>
            Alimento completo y balanceado para perros adultos, 
            formulado por Pedigree para satisfacer las necesidades nutricionales de tu mascota.
            Enriquecido con vitaminas, minerales y proteínas de alta calidad para apoyar la salud y vitalidad de tu perro.
            <p id="modalText">
                <br>

            </p>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Salir</button>
            <a href=""> <!-- *Link al perro -->
                <button type="button" class="btn btn-primary">Not Exit</button> 
            </a>
        </div>
        </div>
    </div>
</div>

{% comment %} modalCorreaMascota {% endcomment %}
<div class="modal fade" id="modalCorreaMascota" tabindex="-1" aria-labelledby="modalCorreaMascota" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h1 class="modal-title fs-5" id="modalCorreaMascota">Castillo de Gato</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <img src="../static/img/Productos/Accesorios/Correa Mascota.jpg" alt="100" height="300" width="300">
            <hr>
            La correa de perro reflectante Lazer Brite® mantiene a su perro seguro 
            y fácilmente visible con material reflectante, asegurando una visibilidad 
            a la distancia.
            <p id="modalText">
                <br>

            </p>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Salir</button>
            <a href=""> <!-- *Link al perro -->
                <button type="button" class="btn btn-primary">Not Exit</button> 
            </a>
        </div>
        </div>
    </div>
</div>

{% comment %} modalBolsa {% endcomment %}
<div class="modal fade" id="modalBolsa" tabindex="-1" aria-labelledby="modalBolsa" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h1 class="modal-title fs-5" id="modalBolsa">Castillo de Gato</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <img src="../static/img/Productos/Higiene/Bolsas.jpg" alt="100" height="300" width="300">
            <hr>
            Conjunto de herramientas ergonómicas para limpiar los desechos de mascotas de manera rápida y eficiente. 
            Ideal para mantener la higiene en interiores y exteriores.
            a la distancia.
            <p id="modalText">
                <br>

            </p>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Salir</button>
            <a href=""> <!-- *Link al perro -->
                <button type="button" class="btn btn-primary">Not Exit</button> 
            </a>
        </div>
        </div>
    </div>
</div>

{% comment %} modalJugueteMascotaa {% endcomment %}
<div class="modal fade" id="modalJugueteMascotaa" tabindex="-1" aria-labelledby="modalJugueteMascotaa" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h1 class="modal-title fs-5" id="modalJugueteMascotaa">Castillo de Gato</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <img src="../static/img/Productos/Accesorios/JugeteMascota.jpg" alt="100" height="300" width="300">
            <hr>
            Está fabricado con goma resistente de alta calidad, diseñada 
            para soportar el juego más enérgico de tu mascota. No importa cuánto 
            muerda o tire, este juguete resistirá el paso del tiempo.
            <p id="modalText">
                <br>

            </p>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Salir</button>
            <a href=""> <!-- *Link al perro -->
                <button type="button" class="btn btn-primary">Not Exit</button> 
            </a>
        </div>
        </div>
    </div>
</div>

{% comment %} modalComidaCachorro {% endcomment %}
<div class="modal fade" id="modalComidaCachorro" tabindex="-1" aria-labelledby="modalComidaCachorro" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h1 class="modal-title fs-5" id="modalComidaCachorro">Castillo de Gato</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <img src="../static/img/Productos/Alimentacion/ComidaCachorro.jpg" alt="100" height="300" width="300">
            <hr>
            Alimento completo y equilibrado diseñado específicamente para cachorros, proporcionando los nutrientes esenciales para un crecimiento saludable y un desarrollo óptimo.
            Desarrollado por Pedigree para apoyar la salud y vitalidad desde temprana edad.
            <p id="modalText">
                <br>

            </p>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Salir</button>
            <a href=""> <!-- *Link al perro -->
                <button type="button" class="btn btn-primary">Not Exit</button> 
            </a>
        </div>
        </div>
    </div>
</div>

{% comment %} modalBandanaTipoA {% endcomment %}
<div class="modal fade" id="modalBandanaTipoA" tabindex="-1" aria-labelledby="modalBandanaTipoA" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h1 class="modal-title fs-5" id="modalBandanaTipoA">Castillo de Gato</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <img src="../static/img/Productos/Accesorios/Bandanastipoa.jpg" alt="100" height="300" width="300">
            <hr>
            Hermoso collar eco-cuero para perros tamaño M
            Largo ajustable (cuello): 27 a 34 centímetros.
            Para mascotas con estilo.
            <p id="modalText">
                <br>

            </p>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Salir</button>
            <a href=""> <!-- *Link al perro -->
                <button type="button" class="btn btn-primary">Not Exit</button> 
            </a>
        </div>
        </div>
    </div>
</div>

<script src="{% static 'js/funcion.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

core/PetStore/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">    
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Login</title>
</head>
<body class="img_background">
    {% include 'base/header.html' %}
    <main>
        <br>
        <div class="container">
            <div class="row row-cols-md-4 justify-content-center">
                <h2>Iniciar Sesión</h2>
            </div>
            <br>
            <center>
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_username">Correo</label>
                        {{ form.username }}
                    </div>
                    <br>
                    <div class="form-group">
                        <label for="id_password">Contraseña</label>
                        {{ form.password }}
                    </div>
                </form>
                <br>
                <br>
            </center>
        </div>
        <br>
        <br>
        <div class="row row-cols-md-4 justify-content-center">
            <div class="row row-cols-md-4">
                <a href="{% url "registro" %}">
                    <button class="btn btn-light">
                        Registrarse
                    </button>
                </a>
            </div>
            <div class="col-2">
                <div class="row-6">
                    <button type="submit" class="btn btn-primary">Iniciar sesión</button>
                </div>
            </div>
        </div>
        <br>
        <br>
        <br>
        <br>
    </main>
    {% include 'base/footer.html' %}
    <script src="{% static 'js/funcion.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

core/PetStore/templates/pages/registro.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Registro</title>
</head>

<body class="img_background">
    {% include 'base/header.html' %}
    <main>
        <br>
{% comment %}
        <div class="container">
            <div class="row row-cols-md-4">
                <h2>Registro de usuario</h2>
            </div>
            <br>
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_nombre">Nombre</label>
                    {{ form.nombre }}
                </div>
                <br>
                <div class="form-group">
                    <label for="id_apellidos">Apellidos</label>
                    {{ form.apellidos }}
                </div>
                <br>
                <div class="form-group">
                    <label for="id_email">Correo</label>
                    {{ form.email }}
                </div>
                <br>
                <div class="form-group">
                    <label for="id_pass1">Constraseña</label>
                    {{ form.pass1 }}
                </div>
                <br>
                <div class="form-group">
                    <label for="id_direccion">Dirección</label>
                    {{ form.direccion }}
                </div>
                <br>
                <div class="form-group">
                    <label for="id_region">Región</label>
                    {{ form.region }}
                </div>
                <br>
                <div class="form-group">
                    <label for="id_codZip">Código Postal</label>
                    {{ form.codZip }}
                </div>
                <br>
                <br>
                <button type="submit" class="btn btn-dark">Registrarse</button>
            </form>
        </div>
{% endcomment %}
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Registrar</button>
        </form>
        
    </main>
    {% include 'base/footer.html' %}
    <script src="{% static 'js/funcion.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

core/PetStore/templates/registro.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Registro</title>
</head>

<body class="img_background">
    {% include 'base/header.html' %}
    <main>
        <br>
        <div class="container">
            <div class="row row-cols-md-4">
                <h2>Registro de usuario</h2>
            </div>
            <br>
            <form action="{% url "registro" %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_nombre">Nombre</label>
                    {{ form.username }}
                </div>
                <br>
                <div class="form-group">
                    <label for="id_apellidos">Apellidos</label>
                    {{ form.last_name }}
                </div>
                <br>
                <div class="form-group">
                    <label for="id_email">Correo</label>
                    {{ form.email }}
                </div>
                <br>
                <div class="form-group">
                    <label for="id_pass1">Constraseña</label>
                    {{ form.password1 }}
                </div>
                <br>
                <div class="form-group">
                    <label for="id_pass1">Confirmar Contraseña</label>
                    {{ form.password2 }}
                </div>
                <br>
                <div class="form-group">
                    <label for="id_direccion">Dirección</label>
                    {{ form.direccion }}
                </div>
                <br>
                <div class="form-group">
                    <label for="id_region">Región</label>
                    {{ form.region }}
                </div>
                <br>
                <div class="form-group">
                    <label for="id_codZip">Código Postal</label>
                    {{ form.cod_zip }}
                </div>
                <br>
                <br>
                <button type="submit" class="btn btn-dark">Registrarse</button>
            </form>
        </div>
    </main>
    {% include 'base/footer.html' %}
    <script src="{% static 'js/funcion.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>